# Generated by Django 4.0.3 on 2022-03-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='MASTER BEDROOM', max_length=50, null=True, verbose_name='Set a Name for Service')),
                ('company_name', models.CharField(blank=True, default='RESORT PALACE', max_length=50, null=True, verbose_name='Set a Company Name')),
                ('icon', models.CharField(blank=True, default='w3_road', max_length=20, null=True, verbose_name='Set a Icon Class Name')),
            ],
            options={
                'verbose_name': 'Service Chart',
                'verbose_name_plural': 'Service Chart',
            },
        ),
    ]
