# Generated by Django 4.0.3 on 2022-03-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0002_servicechart'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicechart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
