# Generated by Django 4.0.3 on 2022-03-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0003_servicechart_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='About_Images/', verbose_name='Upload Image for About Section')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='About_Images/', verbose_name='Upload Image for About Section')),
                ('heading', models.CharField(blank=True, default='About Our Resort Palace', max_length=100, null=True, verbose_name='Set a Heading')),
                ('description', models.CharField(blank=True, default='Short Description', max_length=100, null=True, verbose_name='Set a Description')),
                ('offer', models.CharField(blank=True, default="You'll love all the amenities we offer!", max_length=100, null=True, verbose_name='Set a Offer')),
                ('offer_description', models.CharField(blank=True, default='Offer Short Description', max_length=100, null=True, verbose_name='Set a Offer Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
    ]
