# Generated by Django 4.0.3 on 2022-03-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='Ex: Stay First, Pay After or 24 Hours Restaurant', max_length=50, null=True, verbose_name='Set a Heading')),
                ('description', models.CharField(blank=True, default='Short Description', max_length=100, null=True, verbose_name='Set a Description')),
                ('check_point_one', models.CharField(blank=True, default='Check Point One', max_length=30, null=True, verbose_name='Set a Bullet Point')),
                ('icon_class', models.CharField(blank=True, default='fa-clock-o', max_length=20, null=True, verbose_name='Set a Icon Class Name')),
                ('check_point_two', models.CharField(blank=True, default='Check Point Two', max_length=30, null=True, verbose_name='Set a Bullet Point')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Services Section',
                'verbose_name_plural': 'Services Section',
            },
        ),
    ]
