# Generated by Django 4.0.3 on 2022-03-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0005_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='position_class',
            field=models.CharField(blank=True, default='Ex: left or right', max_length=20, null=True, verbose_name='Set a Position Class Name'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon_class',
            field=models.CharField(blank=True, default='Ex: fa-clock-o or fa-credit-card', max_length=20, null=True, verbose_name='Set a Icon Class Name'),
        ),
    ]
