# Generated by Django 4.0.3 on 2022-03-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0006_services_position_class_alter_services_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Ex: John Doe', max_length=50, null=True, verbose_name='Set a Name')),
                ('designation', models.CharField(blank=True, default='Ex: CEO', max_length=50, null=True, verbose_name='Set a Designation')),
                ('short_intro', models.CharField(blank=True, default='Short Description', max_length=100, null=True, verbose_name='Set a Short Intro')),
                ('facebook_link', models.CharField(blank=True, default='https://www.facebook.com/', max_length=100, null=True, verbose_name='Set your Facebook Link')),
                ('twitter_link', models.CharField(blank=True, default='https://www.twitter.com/', max_length=100, null=True, verbose_name='Set your Twitter Link')),
                ('google_plus_link', models.CharField(blank=True, default='https://www.google.com/', max_length=100, null=True, verbose_name='Set your Google Plus Link')),
                ('rss_link', models.CharField(blank=True, default='https://www.rss.com/', max_length=100, null=True, verbose_name='Set your Rss Link')),
                ('tab_name', models.CharField(blank=True, default='Ex: tab1', max_length=100, null=True, verbose_name='Set a Tab Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Team_Images/', verbose_name='Upload Image for Team Section')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Section',
                'verbose_name_plural': 'Team Section',
            },
        ),
    ]
