# Generated by Django 4.0.3 on 2022-03-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0007_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Gallery_Images/', verbose_name='Upload Image for Gallery Section')),
                ('image_tag', models.CharField(blank=True, default='Ex: Resort Palace', max_length=50, null=True, verbose_name='Set a Image Tag')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Section',
                'verbose_name_plural': 'Gallery Section',
            },
        ),
    ]
