# Generated by Django 4.0.3 on 2022-03-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0009_roomsrates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='Visitors_Images/', verbose_name='Upload Back Image for Visitors Section')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='Visitors_Images/', verbose_name='Upload Front Image for Visitors Section')),
                ('title', models.CharField(blank=True, default='Ex: Best Resort', max_length=50, null=True, verbose_name='Set a Title')),
                ('description', models.CharField(blank=True, default='Short Description', max_length=100, null=True, verbose_name='Set a Description')),
                ('name', models.CharField(blank=True, default='Ex: John Doe', max_length=50, null=True, verbose_name='Set a Name')),
                ('location', models.CharField(blank=True, default='Ex: California', max_length=50, null=True, verbose_name='Set a Location')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Visitor Review Section',
                'verbose_name_plural': 'Visitors Review Section',
            },
        ),
    ]
