# Generated by Django 4.0.3 on 2022-03-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0010_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='image',
        ),
    ]
