# Generated by Django 4.0.3 on 2022-03-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0011_remove_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='class_name',
            field=models.CharField(blank=True, default='Ex: w3layouts-banner-top1 or w3layouts-banner-top2 or null', max_length=20, null=True, verbose_name='Set One of these Class Name'),
        ),
    ]
