# Generated by Django 4.0.3 on 2022-03-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0014_savecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='saveChecking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('arrival_date', models.CharField(max_length=50)),
                ('departure_date', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Save Checking info From User',
                'verbose_name_plural': 'Save Checking info From User',
            },
        ),
    ]
