# Generated by Django 4.0.3 on 2022-03-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0015_savechecking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savechecking',
            old_name='arrival_date',
            new_name='adate',
        ),
        migrations.RenameField(
            model_name='savechecking',
            old_name='departure_date',
            new_name='ddate',
        ),
    ]
