# Generated by Django 4.0.3 on 2022-03-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0016_rename_arrival_date_savechecking_adate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savechecking',
            old_name='room_type',
            new_name='roomtype',
        ),
    ]
