# Generated by Django 4.0.3 on 2022-03-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0017_rename_room_type_savechecking_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('check_in', models.CharField(max_length=50)),
                ('check_out', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Set Booking List',
                'verbose_name_plural': 'Set Booking List',
            },
        ),
    ]
