# Generated by Django 4.0.3 on 2022-03-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0018_bookinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('check_in', models.CharField(max_length=50)),
                ('check_out', models.CharField(max_length=50)),
                ('room_price', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Get Booking List',
                'verbose_name_plural': 'Get Booking Lists',
            },
        ),
        migrations.CreateModel(
            name='searchBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('check_in', models.CharField(max_length=50)),
                ('check_out', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='bookinglist',
            table='booking_list',
        ),
    ]
