# Generated by Django 4.0.3 on 2022-03-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0019_booking_searchbooking_alter_bookinglist_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_active',
        ),
    ]
